#!/usr/bin/env bash
# Hook — PreToolUse schema edit guard.
# Blocks direct edits to prisma/schema.prisma. Schema changes are coordinated
# through Kyle — Claude shouldn't be editing the schema file directly.
# Defense in depth alongside the prisma migration gate.

set -uo pipefail

INPUT=$(cat 2>/dev/null || echo '{}')
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)

# Allow if no file path
[ -z "$FILE" ] && exit 0

# Match prisma/schema.prisma at any path depth
case "$FILE" in
  */prisma/schema.prisma|prisma/schema.prisma)
    cat >&2 <<'EOF'
🛑 Schema edits are coordinated through Kyle.

Per CLAUDE.md: the team shares a single dev database. Editing
prisma/schema.prisma directly can cause migration drift and data loss
for the whole team.

DO NOT edit this file. Stop and tell the user:
"Schema changes need Kyle's coordination first. DM him with what you
want to change, and he'll edit the schema and run the migration."
EOF
    exit 2
    ;;
esac

exit 0
