"use client";

import { useState } from "react";
import { useRouter, usePathname } from "next/navigation";
import Image from "next/image";
import NoiseBackground from "@/components/NoiseBackground";
import CTAButton from "@/components/CTAButton";
import CreateRiffModal from "@/components/riffs/CreateRiffModal";

interface Panel {
  id: "write" | "riff" | "club";
  heading: string;
  body: string;
  cta: string;
  accentColor: string;
  rotate: number;
  lift: number;
  quip: string;
  quipRotate: number;
}

// The three domains as a ladder — write alone, riff with friends, club as
// the recurring version of that, left to right. Each is a stamped,
// slightly-off-kilter "sticker" rather than a perfectly aligned card, so
// the trio reads as placed by hand rather than generated by a grid.
const PANELS: Panel[] = [
  {
    id: "write",
    heading: "Write something.",
    body: "Invite some friends to read and comment.",
    cta: "Start writing",
    accentColor: "#01EFFC",
    rotate: -3,
    lift: 0,
    quip: "feeling creative, might delete later",
    quipRotate: -4,
  },
  {
    id: "riff",
    heading: "Write with friends.",
    body: "Submit before the deadline and reveal together.",
    cta: "Start a riff",
    accentColor: "#00FF66",
    rotate: 2,
    lift: -14,
    quip: "literary mosh pit with friends",
    quipRotate: 3,
  },
  {
    id: "club",
    heading: "Riff with friends.",
    body: "Name your group and write every month.",
    cta: "Start a club",
    accentColor: "#EECF01",
    rotate: -2,
    lift: 6,
    quip: "write clubs are the new book clubs",
    quipRotate: -3,
  },
];

function hexToRgba(hex: string, alpha: number): string {
  const value = parseInt(hex.replace("#", ""), 16);
  const r = (value >> 16) & 255;
  const g = (value >> 8) & 255;
  const b = value & 255;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// Sizing shared by all three panel CTAs — bigger than CTAButton's own
// default so it reads as a hero action, not an inline one. Weight is left
// at CTAButton's default (300, the design system's standard button weight).
const panelButtonStyle = {
  padding: "16px 36px",
  fontSize: "17px",
};

interface MyRiffsEmptyStateProps {
  onStartWriting: () => void;
  isCreatingDraft: boolean;
}

export default function MyRiffsEmptyState({
  onStartWriting,
  isCreatingDraft,
}: MyRiffsEmptyStateProps) {
  const router = useRouter();
  const pathname = usePathname();
  const [isRiffModalOpen, setIsRiffModalOpen] = useState(false);
  const [hoveredPanelId, setHoveredPanelId] = useState<Panel["id"] | null>(
    null
  );

  const handleStartClub = () => {
    sessionStorage.setItem("pendingClubFrom", pathname);
    router.push("/onboarding/create-club");
  };

  return (
    <div
      style={{
        position: "relative",
        overflow: "hidden",
        minHeight: "calc(100vh - 70px)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "64px 24px 96px",
        boxSizing: "border-box",
      }}
    >
      {/* Absolutely filled to match the panel's own bounds (not a fixed
          100vh) so it always covers the full container even when the
          panels stack taller than one screen on mobile — no gap to scroll
          into below it. */}
      <div aria-hidden style={{ position: "absolute", inset: 0 }}>
        <Image
          src="/images/about/friendsgiving2025.gif"
          alt=""
          fill
          unoptimized
          priority
          style={{
            objectFit: "cover",
            // Soft enough to keep faces unrecognizable without losing the
            // shapes/colors of the scene. Scaled up slightly so blur doesn't
            // soften the image's own edges into a visible halo.
            filter: "blur(4px)",
            transform: "scale(1.05)",
          }}
        />
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundColor: "rgba(0, 0, 0, 0.85)",
          }}
        />
      </div>

      <NoiseBackground fillMode="cover" style={{ opacity: 0.15 }} />

      <h1
        style={{
          position: "relative",
          zIndex: 1,
          fontFamily: "var(--font-dm-serif-text)",
          fontSize: "96px",
          fontWeight: 400,
          lineHeight: 0.98,
          letterSpacing: "-0.01em",
          color: "#FFFFFF",
          textAlign: "center",
          margin: "0 0 80px 0",
          maxWidth: "900px",
        }}
      >
        Write with friends,{" "}
        <span style={{ fontStyle: "italic" }}>for fun.</span>
      </h1>

      <div
        className="panels"
        style={{
          position: "relative",
          zIndex: 1,
          width: "100%",
          maxWidth: "1000px",
          display: "flex",
          alignItems: "center",
          gap: "56px",
        }}
      >
        {PANELS.map((panel) => (
          <div
            key={panel.id}
            style={{
              flex: 1,
              display: "flex",
              justifyContent: "center",
              transform: `rotate(${panel.rotate}deg) translateY(${panel.lift}px)`,
            }}
          >
            {/* Semi-transparent "sticker card" — a black scrim (legibility)
                plus a thin wash of the panel's own accent (identity), so
                the trio reads as three placed objects instead of text
                floating loose on the photo. Shadow turns the panel's accent
                color on hover — a preview of the CTA's own hover color. */}
            <div
              onMouseEnter={() => setHoveredPanelId(panel.id)}
              onMouseLeave={() => setHoveredPanelId(null)}
              style={{
                position: "relative",
                width: "100%",
                maxWidth: "280px",
                aspectRatio: "4 / 5",
                boxSizing: "border-box",
                padding: "36px 24px 28px",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
                gap: "20px",
                textAlign: "center",
                border: "2px solid #000000",
                boxShadow: `8px 8px 0px 0px ${
                  hoveredPanelId === panel.id ? panel.accentColor : "#000000"
                }`,
                transition: "box-shadow 0.1s ease",
              }}
            >
              {/* Comic speech bubble — the one deliberately rounded shape in
                  this build. Everything else in the design system is sharp
                  corners, but a speech bubble reads as a speech bubble via
                  its curve + tail, so the brutalist "no radius" rule gets a
                  one-off exception here. */}
              <div
                aria-hidden
                style={{
                  position: "absolute",
                  bottom: "100%",
                  left: "50%",
                  marginBottom: "16px",
                  zIndex: 3,
                  width: "max-content",
                  maxWidth: "200px",
                  padding: "12px 16px",
                  backgroundColor: "#FFFFFF",
                  border: "3px solid #000000",
                  borderRadius: "20px",
                  boxShadow: `4px 4px 0px 0px ${panel.accentColor}`,
                  opacity: hoveredPanelId === panel.id ? 1 : 0,
                  transform: `translateX(-50%) rotate(${panel.quipRotate}deg) translateY(${
                    hoveredPanelId === panel.id ? 0 : 8
                  }px)`,
                  transition: "opacity 0.15s ease, transform 0.15s ease",
                  pointerEvents: "none",
                }}
              >
                <p
                  style={{
                    fontFamily: "var(--font-dm-sans)",
                    fontWeight: 700,
                    fontSize: "13px",
                    lineHeight: 1.4,
                    color: "#000000",
                    textAlign: "center",
                    margin: 0,
                  }}
                >
                  {panel.quip}
                </p>
                <div
                  style={{
                    position: "absolute",
                    bottom: "-9px",
                    left: "50%",
                    transform: "translateX(-50%) rotate(45deg)",
                    width: "16px",
                    height: "16px",
                    backgroundColor: "#FFFFFF",
                    borderRight: "3px solid #000000",
                    borderBottom: "3px solid #000000",
                  }}
                />
              </div>

              <div
                aria-hidden
                style={{
                  position: "absolute",
                  inset: 0,
                  backgroundColor: "rgba(0, 0, 0, 0.45)",
                }}
              />
              <div
                aria-hidden
                style={{
                  position: "absolute",
                  inset: 0,
                  backgroundColor: hexToRgba(panel.accentColor, 0.16),
                  mixBlendMode: "screen",
                }}
              />

              <div
                style={{
                  position: "relative",
                  zIndex: 1,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: "32px",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "12px",
                  }}
                >
                  <h2
                    style={{
                      fontFamily: "var(--font-dm-serif-text)",
                      fontSize: "32px",
                      fontWeight: 400,
                      lineHeight: 1.2,
                      color: "#FFFFFF",
                      margin: 0,
                    }}
                  >
                    {panel.heading}
                  </h2>
                  <p
                    style={{
                      fontFamily: "var(--font-dm-sans)",
                      fontSize: "16px",
                      fontWeight: 300,
                      lineHeight: 1.6,
                      color: "rgba(255, 255, 255, 0.8)",
                      margin: 0,
                    }}
                  >
                    {panel.body}
                  </p>
                </div>

                {panel.id === "write" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={onStartWriting}
                    style={panelButtonStyle}
                  >
                    {isCreatingDraft ? "Creating…" : panel.cta}
                  </CTAButton>
                )}

                {panel.id === "riff" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={() => setIsRiffModalOpen(true)}
                    style={panelButtonStyle}
                  >
                    {panel.cta}
                  </CTAButton>
                )}

                {panel.id === "club" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={handleStartClub}
                    style={panelButtonStyle}
                  >
                    {panel.cta}
                  </CTAButton>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <style>{`
        .panels {
          flex-direction: column;
        }
        @media (min-width: 768px) {
          .panels {
            flex-direction: row;
            align-items: flex-start;
            padding-top: 24px;
          }
        }
      `}</style>

      <CreateRiffModal
        isOpen={isRiffModalOpen}
        onClose={() => setIsRiffModalOpen(false)}
        onCreated={(riffId) => {
          setIsRiffModalOpen(false);
          router.push(`/riffs/${riffId}`);
        }}
      />
    </div>
  );
}
