"use client";

import { useState } from "react";
import { useRouter, usePathname } from "next/navigation";
import Image from "next/image";
import NoiseBackground from "@/components/NoiseBackground";
import CTAButton from "@/components/CTAButton";
import CreateRiffModal from "@/components/riffs/CreateRiffModal";

type Shape = "bolt" | "triangle" | "circle";

interface Panel {
  id: "write" | "riff" | "club";
  lines: [string, string];
  cta: string;
  accentColor: string;
  shapeColor: string;
  rotate: number;
  lift: number;
  shape: Shape;
  wobbleDuration: number;
  wobbleDelay: number;
}

// The three domains as a ladder — write alone, riff with friends, club as
// the recurring version of that, left to right. Each is a stamped,
// slightly-off-kilter "sticker" rather than a perfectly aligned card, so
// the trio reads as placed by hand rather than generated by a grid.
const PANELS: Panel[] = [
  {
    id: "write",
    lines: ["Write something.", "Share with a friend."],
    cta: "Start writing",
    accentColor: "#01EFFC",
    shapeColor: "#FF6B35",
    rotate: -3,
    lift: 0,
    shape: "bolt",
    wobbleDuration: 1.1,
    wobbleDelay: 0,
  },
  {
    id: "riff",
    lines: ["Write with friends.", "Reveal together."],
    cta: "Start a riff",
    accentColor: "#00FF66",
    shapeColor: "#955CB5",
    rotate: 2,
    lift: -14,
    shape: "triangle",
    wobbleDuration: 0.9,
    wobbleDelay: 0.15,
  },
  {
    id: "club",
    lines: ["Riff with friends.", "Every month."],
    cta: "Start a club",
    accentColor: "#EECF01",
    shapeColor: "#C01582",
    rotate: -2,
    lift: 6,
    shape: "circle",
    wobbleDuration: 1.3,
    wobbleDelay: 0.3,
  },
];

function hexToRgba(hex: string, alpha: number): string {
  const value = parseInt(hex.replace("#", ""), 16);
  const r = (value >> 16) & 255;
  const g = (value >> 8) & 255;
  const b = value & 255;
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const SHAPE_CLIP_PATH: Record<Shape, string | undefined> = {
  // Fat wedge head tapering into a thin jagged tail, instead of a uniform
  // zigzag stroke.
  bolt: "polygon(30% 0%, 78% 0%, 42% 42%, 68% 42%, 26% 100%, 42% 52%, 10% 52%)",
  // Scalene, not isoceles — an off-center apex and an uneven base so it
  // reads as lopsided rather than a clean, centered triangle.
  triangle: "polygon(38% 0%, 0% 78%, 100% 100%)",
  circle: undefined,
};

// Flat color + black border + hard drop-shadow + a clipped noise texture
// inside the shape's own outline. A regular CSS `border` doesn't trace a
// clip-path outline (it clips away with the box), so the border is a
// second, slightly larger black copy of the same shape sitting behind an
// inset color copy — same trick as a drop-shadow, just with no offset.
function ShapeIcon({
  shape,
  color,
  wobbleDuration,
  wobbleDelay,
}: {
  shape: Shape;
  color: string;
  wobbleDuration: number;
  wobbleDelay: number;
}) {
  const borderRadius = shape === "circle" ? "50%" : 0;
  // A circle spinning in place shows no visible motion at all — it needs a
  // squash-stretch bounce instead of the rotational wobble the other two
  // (asymmetric) shapes use.
  const animationClass = shape === "circle" ? "shape-bounce" : "shape-wobble";

  return (
    <div
      className={`shape-icon ${animationClass}`}
      style={{
        width: "72px",
        height: "72px",
        filter: "drop-shadow(6px 6px 0px #000000)",
        animationDuration: `${wobbleDuration}s`,
        animationDelay: `${wobbleDelay}s`,
      }}
    >
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          backgroundColor: "#000000",
          borderRadius,
          clipPath: SHAPE_CLIP_PATH[shape],
        }}
      >
        <div
          style={{
            position: "absolute",
            inset: "3px",
            overflow: "hidden",
            backgroundColor: color,
            borderRadius,
            clipPath: SHAPE_CLIP_PATH[shape],
          }}
        >
          {/* NoiseBackground's own SVG paints an opaque white rect before
              the speckles — multiply blends that white away so the flat
              color shows through with just the black grain on top. */}
          <NoiseBackground
            fillMode="cover"
            style={{ mixBlendMode: "multiply" }}
          />
        </div>
      </div>
    </div>
  );
}

// Sizing shared by all three panel CTAs — bigger than CTAButton's own
// default so it reads as a hero action, not an inline one. Weight is left
// at CTAButton's default (300, the design system's standard button weight).
const panelButtonStyle = {
  padding: "16px 36px",
  fontSize: "17px",
};

interface MyRiffsEmptyStateProps {
  onStartWriting: () => void;
  isCreatingDraft: boolean;
}

export default function MyRiffsEmptyState({
  onStartWriting,
  isCreatingDraft,
}: MyRiffsEmptyStateProps) {
  const router = useRouter();
  const pathname = usePathname();
  const [isRiffModalOpen, setIsRiffModalOpen] = useState(false);

  const handleStartClub = () => {
    sessionStorage.setItem("pendingClubFrom", pathname);
    router.push("/onboarding/create-club");
  };

  return (
    <div
      style={{
        position: "relative",
        overflow: "hidden",
        minHeight: "calc(100vh - 70px)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "64px 24px 96px",
        boxSizing: "border-box",
      }}
    >
      {/* Absolutely filled to match the panel's own bounds (not a fixed
          100vh) so it always covers the full container even when the
          panels stack taller than one screen on mobile — no gap to scroll
          into below it. */}
      <div aria-hidden style={{ position: "absolute", inset: 0 }}>
        <Image
          src="/images/about/friendsgiving2025.gif"
          alt=""
          fill
          unoptimized
          priority
          style={{ objectFit: "cover" }}
        />
        <div
          style={{
            position: "absolute",
            inset: 0,
            backgroundColor: "rgba(0, 0, 0, 0.85)",
          }}
        />
      </div>

      <NoiseBackground fillMode="cover" style={{ opacity: 0.15 }} />

      <h1
        style={{
          position: "relative",
          zIndex: 1,
          fontFamily: "var(--font-dm-serif-text)",
          fontSize: "96px",
          fontWeight: 400,
          lineHeight: 0.98,
          letterSpacing: "-0.01em",
          color: "#FFFFFF",
          textAlign: "center",
          margin: "0 0 80px 0",
          maxWidth: "900px",
        }}
      >
        Write with friends,{" "}
        <span style={{ fontStyle: "italic" }}>for fun.</span>
      </h1>

      <div
        className="panels"
        style={{
          position: "relative",
          zIndex: 1,
          width: "100%",
          maxWidth: "1000px",
          display: "flex",
          alignItems: "center",
          gap: "56px",
        }}
      >
        {PANELS.map((panel) => (
          <div
            key={panel.id}
            style={{
              flex: 1,
              display: "flex",
              justifyContent: "center",
              transform: `rotate(${panel.rotate}deg) translateY(${panel.lift}px)`,
            }}
          >
            {/* Semi-transparent "sticker card" — a black scrim (legibility)
                plus a thin wash of the panel's own accent (identity), so
                the trio reads as three placed objects instead of text
                floating loose on the photo. White border/shadow instead of
                the usual black — a black brutal shadow disappears against
                a dark photo the way the nav dropdown's shadow would on a
                dark navbar. */}
            <div
              style={{
                position: "relative",
                width: "100%",
                maxWidth: "280px",
                boxSizing: "border-box",
                padding: "36px 24px 28px",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "20px",
                textAlign: "center",
                border: "2px solid #FFFFFF",
                boxShadow: `8px 8px 0px 0px ${panel.accentColor}`,
              }}
            >
              <div
                aria-hidden
                style={{
                  position: "absolute",
                  inset: 0,
                  backgroundColor: "rgba(0, 0, 0, 0.45)",
                }}
              />
              <div
                aria-hidden
                style={{
                  position: "absolute",
                  inset: 0,
                  backgroundColor: hexToRgba(panel.accentColor, 0.16),
                  mixBlendMode: "screen",
                }}
              />

              <div
                style={{
                  position: "relative",
                  zIndex: 1,
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: "20px",
                }}
              >
                <ShapeIcon
                  shape={panel.shape}
                  color={panel.shapeColor}
                  wobbleDuration={panel.wobbleDuration}
                  wobbleDelay={panel.wobbleDelay}
                />

                <p
                  style={{
                    fontFamily: "var(--font-dm-sans)",
                    fontSize: "20px",
                    fontWeight: 700,
                    lineHeight: 1.4,
                    color: "#FFFFFF",
                    margin: 0,
                  }}
                >
                  {panel.lines[0]}
                  <br />
                  {panel.lines[1]}
                </p>

                {panel.id === "write" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={onStartWriting}
                    style={panelButtonStyle}
                  >
                    {isCreatingDraft ? "Creating…" : panel.cta}
                  </CTAButton>
                )}

                {panel.id === "riff" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={() => setIsRiffModalOpen(true)}
                    style={panelButtonStyle}
                  >
                    {panel.cta}
                  </CTAButton>
                )}

                {panel.id === "club" && (
                  <CTAButton
                    accentColor={panel.accentColor}
                    onClick={handleStartClub}
                    style={panelButtonStyle}
                  >
                    {panel.cta}
                  </CTAButton>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <style>{`
        .panels {
          flex-direction: column;
        }
        @media (min-width: 768px) {
          .panels {
            flex-direction: row;
            align-items: flex-start;
            padding-top: 24px;
          }
        }
        @keyframes shape-wobble {
          0%, 100% { transform: rotate(-16deg); }
          50% { transform: rotate(16deg); }
        }
        @keyframes shape-bounce {
          0%, 100% { transform: translateY(0) scale(1, 1); }
          20% { transform: translateY(2px) scale(1.12, 0.88); }
          55% { transform: translateY(-20px) scale(0.9, 1.12); }
          80% { transform: translateY(0) scale(1.08, 0.94); }
        }
        .shape-icon {
          animation-timing-function: ease-in-out;
          animation-iteration-count: infinite;
        }
        .shape-icon.shape-wobble {
          animation-name: shape-wobble;
        }
        .shape-icon.shape-bounce {
          animation-name: shape-bounce;
        }
        @media (prefers-reduced-motion: reduce) {
          .shape-icon {
            animation: none;
          }
        }
      `}</style>

      <CreateRiffModal
        isOpen={isRiffModalOpen}
        onClose={() => setIsRiffModalOpen(false)}
        onCreated={(riffId) => {
          setIsRiffModalOpen(false);
          router.push(`/riffs/${riffId}`);
        }}
      />
    </div>
  );
}
